matrix:
  include:
    - language: node_js
      node_js:
        - '6.14' # previous LTS, currently in EPEL
        - '8' # current LTS
        - '10' # future LTS
      script: ./script/travis_run_js_tests.sh
      - language: ruby
        rvm:
          - 2.4.1
        script:
           - bundle exec rake db:create --all
           - bundle exec rake db:migrate
           - bundle exec rake db:seeds
        services:
          - postgresql

