language: node_js
node_js:
  - 9.11.2                                                      # choose your version
addons:
  postgresql: "9.4"                                             # choose your version
services:                                             # redis is not necessary, https://redis.io/
  - postgresql
cache:
  bundler: true                                                 # cache for bundler
  npm: true                                                    # cache for npm
  directories:
    - /home/travis/.cache/Cypress                                       # cache for bundler in node environement                                                # cache travis
    - node_modules
before_install:
  - sudo apt-get install libsystemd-journal-dev
  - sudo apt-get build-dep vagrant ruby-libvirt
  - sudo apt-get install qemu libvirt-bin ebtables dnsmasq
  - sudo apt-get install libxslt-dev libxml2-dev libvirt-dev zlib1g-dev ruby-dev
  - gem install bundler                                         # install bundler
  - bundle install                                              # install dependancies in your gemfile
install:
  - npm install                                           # install npm
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres       # create database test
  - cp config/database.yml.travis config/database.yml
  - RAILS_ENV=test bundle exec rake db:migrate            # create database with table
  - SEED_ADMIN_PASSWORD=1234 RAILS_ENV=test bundle exec rake db:seed                   # launch your seed
  - RAILS_ENV=test bundle exec rake assets:precompile                          # compile assets js
  - RAILS_ENV=test bundle exec rake webpack:compile
  - RAILS_ENV=test bundle exec foreman start rails &                                          # launch server rails
  - sleep 12
script:
  - cypress run --record --key 9de1d57d-763b-4a9e-a5a6-c7eee4983ec7                         # launch your frontend test with Cypress